[package]
name = "jami-cli"
description = "Jami client for terminal"
version = "0.5.0"
authors = ["Sébastien Blin <amarok@enconn.fr>"]
edition = "2018"
keywords = ["jami", "tui"]
repository = "https://github.com/AmarOk1412/jami-cli"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities"]

[badges]
gitlab = { repository = "https://github.com/AmarOk1412/jami-cli", branch = "master" }

[dependencies]
app_dirs = "1.2.1"
anyhow = "1.0.32"
base64 = "0.12.3"
chrono = { version = "0.4.13", features = ["serde"] }
crossterm = { version = "0.17.7", features = ["event-stream"] }
dirs = "3.0.1"
log = "0.4.11"
itertools = "0.9.0"
rusqlite = "0.24.2"
scopeguard = "1.1.0"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
structopt = "0.3.15"
textwrap = "0.12.1"
thiserror = "1.0.20"
tokio = { version = "0.2.22", features = ["full"] }
toml = "0.5.6"
tui = { version = "0.12.0", default-features = false, features = ["crossterm"] }
unicode-width = "0.1.8"
#jami-rs = "0.3.0"
jami-rs = { git = "https://github.com/8go/jami-rs", branch="main" }
